// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kalougata/gomall/internal/server"
	"github.com/kalougata/gomall/internal/server/http"
)

// Injectors from wire.go:

func NewApp() (*server.Server, func(), error) {
	mallServerHTTP := serverhttp.NewMallServerHTTP()
	adminServerHTTP := serverhttp.NewAdminServerHTTP()
	serverServer := server.NewServer(mallServerHTTP, adminServerHTTP)
	return serverServer, func() {
	}, nil
}
