// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kalougata/gomall/api/v1/admin"
	"github.com/kalougata/gomall/api/v1/mall"
	"github.com/kalougata/gomall/internal/controller/admin"
	"github.com/kalougata/gomall/internal/controller/mall"
	"github.com/kalougata/gomall/internal/data"
	"github.com/kalougata/gomall/internal/repo/admin"
	"github.com/kalougata/gomall/internal/server"
	"github.com/kalougata/gomall/internal/server/http"
	"github.com/kalougata/gomall/internal/service/admin"
	"github.com/kalougata/gomall/pkg/config"
	"github.com/kalougata/gomall/pkg/jwt"
)

// Injectors from wire.go:

func NewApp() (*server.Server, func(), error) {
	mallPingController := mallctrl.NewPingController()
	mallAPIRouter := mallapi.NewMallAPIRouter(mallPingController)
	mallServerHTTP := serverhttp.NewMallServerHTTP(mallAPIRouter)
	adminPingController := adminctrl.NewPingController()
	configConfig := config.New()
	dataData, cleanup, err := data.NewData(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepo := adminrepo.NewUserRepo(dataData)
	jwtJWT := jwt.New(configConfig)
	userService := adminsrv.NewUserService(userRepo, jwtJWT)
	userController := adminctrl.NewUserController(userService)
	adminAPIRouter := adminapi.NewAdminAPIRouter(adminPingController, userController)
	adminServerHTTP := serverhttp.NewAdminServerHTTP(adminAPIRouter)
	serverServer := server.NewServer(mallServerHTTP, adminServerHTTP)
	return serverServer, func() {
		cleanup()
	}, nil
}
