// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/kalougata/gomall/api/v1/admin"
	"github.com/kalougata/gomall/api/v1/mall"
	"github.com/kalougata/gomall/internal/controller/admin"
	"github.com/kalougata/gomall/internal/controller/mall"
	"github.com/kalougata/gomall/internal/server"
	"github.com/kalougata/gomall/internal/server/http"
)

// Injectors from wire.go:

func NewApp() (*server.Server, func(), error) {
	mallPingController := mallctrl.NewPingController()
	mallAPIRouter := mallapi.NewMallAPIRouter(mallPingController)
	mallServerHTTP := serverhttp.NewMallServerHTTP(mallAPIRouter)
	adminPingController := adminctrl.NewPingController()
	adminAPIRouter := adminapi.NewAdminAPIRouter(adminPingController)
	adminServerHTTP := serverhttp.NewAdminServerHTTP(adminAPIRouter)
	serverServer := server.NewServer(mallServerHTTP, adminServerHTTP)
	return serverServer, func() {
	}, nil
}
